version: '3.8'

services:

  tests_password_app:
    container_name: tests_password_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@password_app:5432/password_db
    command: pytest -vv
    networks:
      - test_network
    depends_on:
      db_postgres:
        condition: service_healthy


networks:
  test_network:
    external: true
    name: web_network
