name: linter
  # run linter flake8 for project
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '^3.10'
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run linter
        run: |
          make lint
